import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Archive, ArrowLeft, ArrowRight, BadgeCheck, BookOpenCheck, File, FileSearch, HardDrive, Languages, Loader2, LockKeyhole, Search, Sparkles, Trash2, UploadCloud } from 'lucide-react';
import { importVaultFile, loadVaultSources, removeVaultSource, searchVault, type VaultHit, type VaultSource } from '@/lib/knowledgeVault';

const copy = {
  ar: { eyebrow: 'خزانة المعرفة', title: 'مادتك الدراسية تبقى عندك—والبحث يوضح لماذا وجدها.', body: 'ارفع PDF أو نصًا أو Markdown أو CSV. يستخرج فَهيم النص داخل المتصفح، يقسمه إلى مقاطع، ويرتّب الدليل باستخدام BM25 وتغطية المصطلحات والجسر العربي/الإنجليزي دون رفع الملف إلى خادم.', upload: 'أضف مصادر', supported: 'PDF · TXT · MD · CSV · JSON · HTML — حتى 15MB', privacy: 'معالجة محلية وIndexedDB. لا تُرفع الملفات إلى فَهيم في هذا الإصدار.', search: 'ابحث داخل مصادرك', placeholder: 'ما الفرق بين الانقسام المتساوي والمنصف؟', ask: 'اسأل فَهيم بهذه الأدلة', sources: 'مصادرك', chunks: 'مقطع مفهرس', empty: 'لم تضف مصدرًا بعد.', noHits: 'لا توجد مقاطع كافية الصلة. جرّب مصطلحًا أدق أو اسأل بالعربية أو الإنجليزية.', delete: 'حذف المصدر', importing: 'استخراج وفهرسة الملف', tooLarge: 'حجم الملف أكبر من 15MB.', unsupported: 'نوع الملف غير مدعوم.', failed: 'تعذر قراءة الملف. قد يكون محميًا أو تالفًا.', ocrRequired: 'هذا PDF مصوّر ولا يحتوي طبقة نص. حفاظًا على الخصوصية لم نرسله تلقائيًا لخدمة OCR خارجية؛ استخدم نسخة نصية قابلة للبحث.', localRag: 'استرجاع محلي قابل للتفسير', result: 'أدلة مسترجعة', characters: 'حرف' },
  en: { eyebrow: 'Knowledge vault', title: 'Your study material stays with you—and retrieval explains why it matched.', body: 'Upload PDF, text, Markdown, CSV, JSON, or HTML. Fahim extracts text in the browser and ranks evidence with BM25, term coverage, and an Arabic/English concept bridge without uploading the file.', upload: 'Add sources', supported: 'PDF · TXT · MD · CSV · JSON · HTML — up to 15MB', privacy: 'Local processing and IndexedDB. Files are not uploaded to Fahim in this release.', search: 'Search your sources', placeholder: 'What is the difference between mitosis and meiosis?', ask: 'Ask Fahim with this evidence', sources: 'Your sources', chunks: 'indexed chunks', empty: 'You have not added a source yet.', noHits: 'No passage is relevant enough. Try a more precise term or search in Arabic or English.', delete: 'Delete source', importing: 'Extracting and indexing', tooLarge: 'The file is larger than 15MB.', unsupported: 'This file type is not supported.', failed: 'The file could not be read. It may be protected or damaged.', ocrRequired: 'This is an image-only PDF with no text layer. To protect privacy, Fahim did not silently send it to an external OCR service; use a searchable text copy.', localRag: 'Explainable local retrieval', result: 'Retrieved evidence', characters: 'characters' },
} as const;

const reasonCopy = {
  exact_phrase: { ar: 'عبارة مطابقة', en: 'Exact phrase' },
  bilingual_bridge: { ar: 'جسر عربي/إنجليزي', en: 'Bilingual bridge' },
  term_coverage: { ar: 'تغطية المصطلحات', en: 'Term coverage' },
  rare_term: { ar: 'مصطلح مميز', en: 'Distinctive term' },
} as const;

export default function KnowledgeVault({ language }: { language: 'ar' | 'en' }) {
  const t = copy[language]; const navigate = useNavigate(); const Arrow = language === 'ar' ? ArrowLeft : ArrowRight;
  const [sources, setSources] = useState<VaultSource[]>([]); const [query, setQuery] = useState(''); const [hits, setHits] = useState<VaultHit[]>([]);
  const [importing, setImporting] = useState(false); const [error, setError] = useState('');
  useEffect(() => { void loadVaultSources().then(setSources); }, []);
  const totalChunks = useMemo(() => sources.reduce((sum, source) => sum + source.chunks.length, 0), [sources]);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => {
    const files = [...(event.target.files || [])]; if (!files.length) return; setImporting(true); setError('');
    try { for (const file of files) await importVaultFile(file); setSources(await loadVaultSources()); }
    catch (reason) { const code = (reason as Error).message; setError(code === 'file-too-large' ? t.tooLarge : code === 'unsupported-file' ? t.unsupported : code === 'ocr-required' ? t.ocrRequired : t.failed); }
    finally { setImporting(false); event.target.value = ''; }
  };
  const submit = (event: FormEvent) => { event.preventDefault(); setHits(searchVault(sources, query)); };
  const ask = () => {
    const context = hits.slice(0, 5).map((hit, index) => ({ id: hit.chunk.sourceId, citationId: `U${index + 1}`, title: `${hit.chunk.sourceName} · ${hit.location}`, text: hit.chunk.text.slice(0, 900) }));
    sessionStorage.setItem('fahim-vault-handoff', JSON.stringify(context));
    navigate(`/ask-fahim?vault=1&q=${encodeURIComponent(query)}`);
  };
  const remove = async (id: string) => { await removeVaultSource(id); setSources((items) => items.filter((item) => item.id !== id)); setHits((items) => items.filter((item) => item.chunk.sourceId !== id)); };

  return <main className="min-h-[80vh] bg-[var(--surface)] pb-20"><section className="atlas-grid border-b border-[var(--border)] bg-[var(--paper)] py-14 dark:bg-[#0b1116] sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="atlas-kicker"><Archive className="h-4 w-4" />{t.eyebrow}</p><div className="mt-5 grid gap-8 lg:grid-cols-[1fr_22rem] lg:items-end"><div><h1 className="atlas-display max-w-4xl text-4xl sm:text-6xl">{t.title}</h1><p className="mt-5 max-w-3xl leading-8 text-[var(--muted)]">{t.body}</p></div><label className="atlas-upload"><input type="file" multiple accept=".pdf,.txt,.md,.csv,.json,.html,.htm" onChange={upload} className="sr-only" /><span className="grid h-11 w-11 place-items-center bg-[#173F5F] text-white"><UploadCloud className="h-5 w-5" /></span><span><strong className="block text-sm font-black text-[var(--text)]">{importing ? t.importing : t.upload}</strong><small className="mt-1 block text-[10px] font-bold text-[var(--muted)]">{t.supported}</small></span>{importing ? <Loader2 className="ms-auto h-4 w-4 animate-spin text-[#0F766E]" /> : null}</label></div><p className="mt-5 flex items-center gap-2 text-xs font-bold text-[#0F766E]"><LockKeyhole className="h-4 w-4" />{t.privacy}</p></div></section>
    <div className="mx-auto grid max-w-7xl gap-8 px-4 pt-8 sm:px-6 lg:grid-cols-[19rem_1fr] lg:px-8"><aside><div className="flex items-center justify-between border-b-2 border-[var(--text)] pb-3"><h2 className="text-sm font-black text-[var(--text)]">{t.sources}</h2><span className="text-[10px] font-black text-[#D95D39]">{sources.length} · {totalChunks} {t.chunks}</span></div>{sources.length ? <div className="divide-y divide-[var(--border)]">{sources.map((source) => <article key={source.id} className="py-4"><div className="flex gap-3"><File className="mt-1 h-4 w-4 shrink-0 text-[#173F5F] dark:text-blue-200" /><div className="min-w-0 flex-1"><p className="truncate text-xs font-black text-[var(--text)]">{source.name}</p><p className="mt-1 text-[9px] font-bold text-[var(--muted)]">{source.chunks.length} {t.chunks} · {new Intl.NumberFormat(language === 'ar' ? 'ar-EG' : 'en').format(source.characterCount)} {t.characters}</p></div><button type="button" onClick={() => void remove(source.id)} aria-label={t.delete} title={t.delete} className="text-[var(--muted)] hover:text-[#D95D39]"><Trash2 className="h-3.5 w-3.5" /></button></div></article>)}</div> : <div className="py-10 text-center"><HardDrive className="mx-auto h-7 w-7 text-[var(--muted)]" /><p className="mt-3 text-xs font-bold text-[var(--muted)]">{t.empty}</p></div>}</aside>
      <section className="min-w-0"><form onSubmit={submit} className="atlas-search"><label className="relative flex-1"><FileSearch className="absolute start-4 top-1/2 h-5 w-5 -translate-y-1/2 text-[var(--muted)]" /><span className="sr-only">{t.search}</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.placeholder} className="h-16 w-full bg-transparent pe-4 ps-12 text-sm font-bold text-[var(--text)] outline-none" /></label><button disabled={query.trim().length < 3 || !sources.length} className="atlas-search-button"><Search className="h-4 w-4" />{t.search}</button></form>{error ? <div role="alert" className="atlas-notice mt-5 border-[#D95D39]/30 text-[#9c321b]">{error}</div> : null}
        {hits.length ? <><div className="mt-8 flex flex-wrap items-end justify-between gap-4 border-b-2 border-[var(--text)] pb-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#D95D39]">{t.localRag}</p><h2 className="mt-1 text-xl font-black text-[var(--text)]">{hits.length} {t.result}</h2><p className="mt-2 text-xs text-[var(--muted)]">{language === 'ar' ? 'الثقة هنا تصف قوة المطابقة، وليست حكمًا على صحة المحتوى.' : 'Confidence describes retrieval strength—not the truth of the source.'}</p></div><button type="button" onClick={ask} className="inline-flex min-h-11 items-center gap-2 bg-[#173F5F] px-4 py-3 text-xs font-black text-white hover:bg-[#0F766E]"><Sparkles className="h-4 w-4" />{t.ask}<Arrow className="h-4 w-4" /></button></div><div className="divide-y divide-[var(--border)]">{hits.map((hit, index) => <article key={hit.chunk.id} className="grid gap-4 py-6 sm:grid-cols-[3rem_1fr]"><span className="atlas-index">U{index + 1}</span><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-black text-[#173F5F] dark:text-blue-200">{hit.chunk.sourceName}</p><span className="text-[9px] font-bold text-[var(--muted)]">{hit.location}</span><span className={`vault-confidence vault-confidence-${hit.confidence}`}><BadgeCheck className="h-3 w-3" />{hit.confidence === 'high' ? (language === 'ar' ? 'مطابقة قوية' : 'Strong match') : hit.confidence === 'medium' ? (language === 'ar' ? 'مطابقة متوسطة' : 'Medium match') : (language === 'ar' ? 'استكشافية' : 'Exploratory')}</span></div><div className="mt-3 flex flex-wrap gap-2">{hit.reasons.map((reason) => <span key={reason} className="vault-reason">{reason === 'bilingual_bridge' ? <Languages className="h-3 w-3" /> : null}{reasonCopy[reason][language]}</span>)}<span className="vault-reason">{Math.round(hit.coverage * 100)}% {language === 'ar' ? 'تغطية السؤال' : 'query coverage'}</span></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-[var(--muted)]">{hit.excerpt}</p></div></article>)}</div></> : query.length > 2 ? <div className="mt-12 grid min-h-40 place-items-center border-y border-dashed border-[var(--border)] text-xs font-bold text-[var(--muted)]"><BookOpenCheck className="mb-3 h-6 w-6" />{t.noHits}</div> : null}
      </section></div>
  </main>;
}
