import { useMemo, useState } from 'react';
import { readScopedJson, writeScopedJson } from '@/lib/userScope';
import {
  ArrowLeft,
  ArrowRight,
  BarChart3,
  BookOpenCheck,
  BrainCircuit,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  AlertCircle,
  ExternalLink,
  Loader2,
  RotateCcw,
  ShieldCheck,
  Target,
  X,
} from 'lucide-react';
import { generateQuiz, gradeQuizAnswer, type GeneratedQuiz, type GradeResult, type QuizDifficulty } from '@/lib/quiz';
import { getMasteryStats, saveQuizAttempt, type QuizAttempt } from '@/lib/mastery';
import { recordStudyAction } from '@/lib/studyProgress';
import { normalizeMisconception, saveLearningSession, scheduleReviewFromScore, type LearningEvent, type LearningSession } from '@/lib/learningEvidence';
import { syncLearningSession } from '@/lib/supabase/learningEvidenceSync';
import { useSearchParams } from 'react-router-dom';
import LearningEvidencePanel from '@/components/learning/LearningEvidencePanel';

type Props = { language: 'ar' | 'en' };

const copy = {
  ar: {
    eyebrow: 'مختبر الإتقان',
    title: 'اختبر فهمك، واكتشف نقطة الضعف التالية.',
    body: 'اختبار تكويني يولّده فَهيم في صورة منظمة، ويُصحَّح على الخادم دون إرسال الإجابة الصحيحة إلى المتصفح مسبقًا.',
    topic: 'الموضوع',
    topicHint: 'مثال: قانون نيوتن الثاني وتطبيقاته',
    subject: 'المادة',
    subjectHint: 'مثال: الفيزياء',
    grade: 'المرحلة أو المستوى',
    gradeHint: 'مثال: الصف الثالث الثانوي',
    difficulty: 'الصعوبة',
    easy: 'تأسيسي',
    medium: 'متوسط',
    hard: 'متقدم',
    generate: 'أنشئ اختبارًا موثوقًا',
    generating: 'فَهيم يبني أسئلة تطبيقية',
    suggestions: ['التفاضل وتطبيقاته', 'الروابط الكيميائية', 'قواعد البيانات', 'الحركة في خط مستقيم'],
    submit: 'تحقق من الإجابة',
    checking: 'جاري التصحيح',
    next: 'السؤال التالي',
    finish: 'اعرض النتيجة',
    correct: 'إجابة صحيحة',
    incorrect: 'تحتاج مراجعة',
    explanation: 'لماذا؟',
    misconception: 'الالتباس المحتمل',
    correctAnswer: 'الإجابة الصحيحة',
    skill: 'المهارة المقاسة',
    question: 'سؤال',
    of: 'من',
    verified: 'تصحيح موقّع على الخادم',
    sources: 'وجهات موثوقة للمراجعة',
    sourcesNote: 'هذه الروابط وجهات تحقق ومراجعة، وليست دليلًا على أن السؤال معتمد رسميًا.',
    result: 'نتيجة جلسة الإتقان',
    mastered: 'إتقان قوي',
    developing: 'فهم قيد البناء',
    revisit: 'ابدأ بمراجعة الأساس',
    score: 'الإجابات الصحيحة',
    mastery: 'درجة الإتقان',
    xp: 'نقاط الخبرة',
    retry: 'اختبار جديد في الموضوع',
    newTopic: 'موضوع آخر',
    history: 'أداءك التراكمي',
    attempts: 'محاولات',
    questions: 'أسئلة مصححة',
    weakest: 'أضعف موضوع',
    noHistory: 'أكمل أول اختبار لتبدأ خريطة الإتقان.',
    error: 'تعذر إنشاء الاختبار الآن. حاول مجددًا بعد قليل.',
    choose: 'اختر إجابة أولًا.',
    topicRequired: 'اكتب موضوعًا واضحًا من 3 أحرف على الأقل.',
    integrity: 'لا تُرسل الإجابات الصحيحة للواجهة قبل التصحيح، وتنتهي صلاحية كل سؤال تلقائيًا.',
    reasoning: 'اشرح لماذا اخترت هذه الإجابة',
    reasoningHint: 'اكتب الفكرة أو القانون أو خطوات الاستدلال التي استخدمتها. لا نبحث عن صياغة مثالية؛ نحتاج أن نفهم طريقة تفكيرك.',
    reasoningRequired: 'اكتب سبب اختيارك في 8 أحرف على الأقل حتى يكون التشخيص مفيدًا.',
    diagnosis: 'تشخيص قابل للمراجعة',
    diagnosisNote: 'هذه فرضية مبنية على إجابتك وتفسيرك، وليست حكمًا نهائيًا على مستواك.',
    intervention: 'تدخل موجّه',
    retryApplication: 'جرّب سؤالًا تطبيقيًا جديدًا',
    attemptRecorded: 'تم تسجيل طريقة التفكير مع المحاولة',
    resultEvidence: 'دليل التعلّم الناتج',
    resultEvidenceBody: 'يعرض هذا السجل نقطة البداية، والالتباس المحتمل، والتدخل، وما يحتاج مراجعة لاحقة.',
  },
  en: {
    eyebrow: 'Mastery lab',
    title: 'Test understanding and reveal the next weak point.',
    body: 'A structured formative assessment generated by Fahim and graded on the server without exposing correct answers to the browser first.',
    topic: 'Topic',
    topicHint: 'Example: Newton’s second law and applications',
    subject: 'Subject',
    subjectHint: 'Example: Physics',
    grade: 'Level or grade',
    gradeHint: 'Example: Grade 12',
    difficulty: 'Difficulty',
    easy: 'Foundation',
    medium: 'Intermediate',
    hard: 'Advanced',
    generate: 'Generate a rigorous quiz',
    generating: 'Fahim is building application questions',
    suggestions: ['Calculus applications', 'Chemical bonding', 'Database design', 'Motion in one dimension'],
    submit: 'Check answer',
    checking: 'Checking answer',
    next: 'Next question',
    finish: 'Show result',
    correct: 'Correct answer',
    incorrect: 'Needs review',
    explanation: 'Why?',
    misconception: 'Likely misconception',
    correctAnswer: 'Correct answer',
    skill: 'Measured skill',
    question: 'Question',
    of: 'of',
    verified: 'Server-signed grading',
    sources: 'Trusted review destinations',
    sourcesNote: 'These links are review destinations, not a claim that the quiz is officially accredited.',
    result: 'Mastery session result',
    mastered: 'Strong mastery',
    developing: 'Understanding is developing',
    revisit: 'Revisit the foundation',
    score: 'Correct answers',
    mastery: 'Mastery score',
    xp: 'Experience points',
    retry: 'New quiz on this topic',
    newTopic: 'Choose another topic',
    history: 'Cumulative performance',
    attempts: 'Attempts',
    questions: 'Graded questions',
    weakest: 'Weakest topic',
    noHistory: 'Complete your first quiz to start a mastery map.',
    error: 'The quiz could not be generated right now. Try again shortly.',
    choose: 'Choose an answer first.',
    topicRequired: 'Enter a clear topic with at least 3 characters.',
    integrity: 'Correct answers stay off the client until grading, and every question expires automatically.',
    reasoning: 'Explain why you chose this answer',
    reasoningHint: 'Write the idea, rule, or reasoning steps you used. The wording does not need to be perfect; we need to understand your thinking.',
    reasoningRequired: 'Write at least 8 characters about your reasoning so the diagnosis is useful.',
    diagnosis: 'Reviewable diagnosis',
    diagnosisNote: 'This is a hypothesis based on your answer and reasoning, not a final judgment of your ability.',
    intervention: 'Targeted intervention',
    retryApplication: 'Try a new application question',
    attemptRecorded: 'Reasoning recorded with this attempt',
    resultEvidence: 'Resulting learning evidence',
    resultEvidenceBody: 'This record shows the baseline, likely misconception, intervention, and what needs later review.',
  },
} as const;

export default function QuizLab({ language }: Props) {
  const t = copy[language];
  const [params] = useSearchParams();
  const storedProfile = useMemo(() => readScopedJson<Record<string, string>>('fahim-study-profile', {}), []);
  const [topic, setTopic] = useState(params.get('topic') || storedProfile.topic || '');
  const [subject, setSubject] = useState(storedProfile.subject || '');
  const [grade, setGrade] = useState(storedProfile.grade || '');
  const [difficulty, setDifficulty] = useState<QuizDifficulty>('medium');
  const [quiz, setQuiz] = useState<GeneratedQuiz | null>(null);
  const [index, setIndex] = useState(0);
  const [selected, setSelected] = useState<number | null>(null);
  const [result, setResult] = useState<GradeResult | null>(null);
  const [results, setResults] = useState<GradeResult[]>([]);
  const [reasoning, setReasoning] = useState('');
  const [reasonings, setReasonings] = useState<string[]>([]);
  const [attempt, setAttempt] = useState<QuizAttempt | null>(null);
  const [completedSession, setCompletedSession] = useState<LearningSession | null>(null);
  const [loading, setLoading] = useState(false);
  const [checking, setChecking] = useState(false);
  const [error, setError] = useState('');
  const Arrow = language === 'ar' ? ArrowLeft : ArrowRight;
  const Chevron = language === 'ar' ? ChevronLeft : ChevronRight;
  const question = quiz?.questions[index];

  const startQuiz = async () => {
    if (topic.trim().length < 3) {
      setError(t.topicRequired);
      return;
    }
    setLoading(true);
    setError('');
    setQuiz(null);
    setAttempt(null);
    try {
      const generated = await generateQuiz({ topic: topic.trim(), subject, grade, language, difficulty, count: 5 });
      setQuiz(generated);
      setIndex(0);
      setSelected(null);
      setResult(null);
      setResults([]);
      setReasoning('');
      setReasonings([]);
      setCompletedSession(null);
      writeScopedJson('fahim-study-profile', { topic: topic.trim(), subject, grade });
    } catch {
      setError(t.error);
    } finally {
      setLoading(false);
    }
  };

  const checkAnswer = async () => {
    if (!question || selected === null) {
      setError(t.choose);
      return;
    }
    if (reasoning.trim().length < 8) {
      setError(t.reasoningRequired);
      return;
    }
    setChecking(true);
    setError('');
    try {
      const graded = await gradeQuizAnswer(question.token, selected);
      setResult(graded);
      setResults((items) => [...items, graded]);
      setReasonings((items) => [...items, reasoning.trim()]);
    } catch {
      setError(t.error);
    } finally {
      setChecking(false);
    }
  };

  const advance = () => {
    if (!quiz || !result) return;
    if (index < quiz.questions.length - 1) {
      setIndex((value) => value + 1);
      setSelected(null);
      setResult(null);
      setReasoning('');
      setError('');
      return;
    }
    const completed = saveQuizAttempt({
      quizId: quiz.id,
      topic: quiz.topic,
      subject,
      grade,
      score: results.filter((item) => item.correct).length,
      total: quiz.questions.length,
      xp: results.reduce((sum, item) => sum + item.xp, 0),
      skills: results.map((item) => ({ skill: item.skill, correct: item.correct })),
    });
    recordStudyAction('quiz', quiz.topic);
    const session = createQuizEvidenceSession(quiz, results, reasonings, completed.mastery, language);
    saveLearningSession(session);
    void syncLearningSession(session);
    setCompletedSession(session);
    setAttempt(completed);
  };

  const reset = (keepTopic: boolean) => {
    setQuiz(null);
    setAttempt(null);
    setIndex(0);
    setSelected(null);
    setResult(null);
    setResults([]);
    setReasoning('');
    setReasonings([]);
    setCompletedSession(null);
    setError('');
    if (!keepTopic) setTopic('');
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <main className="min-h-[80vh] bg-[var(--surface)] px-4 py-10 sm:px-6 lg:px-8 lg:py-16">
      <div className="mx-auto max-w-7xl">
        {!quiz && !attempt && (
          <>
            <header className="grid gap-8 lg:grid-cols-[1fr_.65fr] lg:items-end">
              <div>
                <p className="eyebrow w-fit"><BrainCircuit className="h-4 w-4" />{t.eyebrow}</p>
                <h1 className="mt-5 max-w-4xl text-4xl font-black tracking-[-.04em] text-[var(--text)] sm:text-6xl">{t.title}</h1>
                <p className="mt-5 max-w-3xl text-base leading-8 text-[var(--muted)]">{t.body}</p>
              </div>
              <div className="rounded-3xl border border-teal-200 bg-teal-50 p-5 text-teal-950 dark:border-teal-400/20 dark:bg-teal-500/10 dark:text-teal-100">
                <div className="flex items-center gap-2 text-xs font-black"><ShieldCheck className="h-4 w-4" />{t.verified}</div>
                <p className="mt-2 text-xs leading-6 opacity-80">{t.integrity}</p>
              </div>
            </header>

            <div className="mt-10 grid gap-6 lg:grid-cols-[1fr_.38fr]">
              <section className="premium-card p-5 sm:p-8">
                <label className="block">
                  <span className="text-xs font-black text-[var(--muted)]">{t.topic}</span>
                  <textarea value={topic} onChange={(event) => setTopic(event.target.value)} rows={3} maxLength={240} placeholder={t.topicHint} className="mt-2 w-full resize-none rounded-2xl border border-[var(--border)] bg-[var(--soft)] px-4 py-3 text-sm font-bold leading-7 text-[var(--text)] outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-500/10" />
                </label>
                <div className="mt-3 flex flex-wrap gap-2">
                  {t.suggestions.map((item) => <button key={item} type="button" onClick={() => setTopic(item)} className="rounded-full border border-[var(--border)] bg-[var(--panel)] px-3 py-1.5 text-[10px] font-black text-[var(--muted)] hover:border-violet-400 hover:text-violet-700">{item}</button>)}
                </div>
                <div className="mt-5 grid gap-4 sm:grid-cols-2">
                  <Field label={t.subject} value={subject} onChange={setSubject} placeholder={t.subjectHint} />
                  <Field label={t.grade} value={grade} onChange={setGrade} placeholder={t.gradeHint} />
                </div>
                <fieldset className="mt-5">
                  <legend className="text-xs font-black text-[var(--muted)]">{t.difficulty}</legend>
                  <div className="mt-2 grid grid-cols-3 gap-2">
                    {(['easy', 'medium', 'hard'] as QuizDifficulty[]).map((item) => (
                      <button key={item} type="button" aria-pressed={difficulty === item} onClick={() => setDifficulty(item)} className={`rounded-2xl border px-3 py-3 text-xs font-black transition ${difficulty === item ? 'border-violet-600 bg-violet-600 text-white shadow-lg shadow-violet-600/15' : 'border-[var(--border)] bg-[var(--soft)] text-[var(--muted)] hover:border-violet-300'}`}>{t[item]}</button>
                    ))}
                  </div>
                </fieldset>
                {error && <ErrorMessage text={error} />}
                <button type="button" disabled={loading || topic.trim().length < 3} onClick={() => void startQuiz()} className="premium-button mt-6 w-full justify-center disabled:cursor-not-allowed disabled:opacity-50">
                  {loading ? <><Loader2 className="h-4 w-4 animate-spin" />{t.generating}</> : <><BrainCircuit className="h-4 w-4" />{t.generate}<Arrow className="h-4 w-4" /></>}
                </button>
              </section>
              <MasterySummary language={language} />
            </div>
          </>
        )}

        {quiz && !attempt && question && (
          <div className="mx-auto max-w-4xl">
            <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
              <div>
                <p className="eyebrow w-fit"><Target className="h-4 w-4" />{quiz.title}</p>
                <h1 className="mt-4 text-2xl font-black text-[var(--text)] sm:text-3xl">{t.question} {index + 1} {t.of} {quiz.questions.length}</h1>
              </div>
              <div className="min-w-48">
                <div className="flex justify-between text-[10px] font-black text-[var(--muted)]"><span>{Math.round(((index + 1) / quiz.questions.length) * 100)}%</span><span>{question.difficulty}</span></div>
                <div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--soft)]"><div className="h-full rounded-full bg-gradient-to-r from-violet-700 to-teal-500 transition-all" style={{ width: `${((index + 1) / quiz.questions.length) * 100}%` }} /></div>
              </div>
            </header>

            <section className="premium-card mt-7 p-5 sm:p-8">
              <div className="flex items-start gap-3">
                <span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-violet-100 text-sm font-black text-violet-700 dark:bg-violet-500/10 dark:text-violet-300">{index + 1}</span>
                <div>
                  <p className="text-lg font-black leading-8 text-[var(--text)] sm:text-xl">{question.question}</p>
                  <p className="mt-2 text-[10px] font-black uppercase tracking-wider text-[var(--muted)]">{t.skill}: {question.skill}</p>
                </div>
              </div>
              <div className="mt-7 grid gap-3" role="radiogroup" aria-label={question.question}>
                {question.options.map((option, optionIndex) => {
                  const isSelected = selected === optionIndex;
                  const isCorrect = Boolean(result?.correct && result.correctIndex === optionIndex);
                  const isWrongSelection = Boolean(result && isSelected && !result.correct);
                  return (
                    <button
                      type="button"
                      role="radio"
                      aria-checked={isSelected}
                      disabled={Boolean(result)}
                      key={`${question.id}-${optionIndex}`}
                      onClick={() => setSelected(optionIndex)}
                      className={`flex items-center gap-3 rounded-2xl border p-4 text-start text-sm font-bold leading-7 transition ${
                        isCorrect ? 'border-teal-500 bg-teal-50 text-teal-950 dark:bg-teal-500/10 dark:text-teal-100'
                          : isWrongSelection ? 'border-rose-500 bg-rose-50 text-rose-950 dark:bg-rose-500/10 dark:text-rose-100'
                            : isSelected ? 'border-violet-600 bg-violet-50 text-violet-950 dark:bg-violet-500/10 dark:text-violet-100'
                              : 'border-[var(--border)] bg-[var(--soft)] text-[var(--text)] hover:border-violet-300'
                      }`}
                    >
                      <span className={`grid h-8 w-8 shrink-0 place-items-center rounded-xl border text-xs font-black ${isCorrect ? 'border-teal-500 bg-teal-500 text-white' : isWrongSelection ? 'border-rose-500 bg-rose-500 text-white' : isSelected ? 'border-violet-600 bg-violet-600 text-white' : 'border-[var(--border)] bg-[var(--panel)] text-[var(--muted)]'}`}>
                        {isCorrect ? <Check className="h-4 w-4" /> : isWrongSelection ? <X className="h-4 w-4" /> : String.fromCharCode(65 + optionIndex)}
                      </span>
                      {option}
                    </button>
                  );
                })}
              </div>

              <label className="assessment-reasoning">
                <span>{t.reasoning}</span>
                <textarea
                  value={reasoning}
                  onChange={(event) => setReasoning(event.target.value)}
                  disabled={Boolean(result)}
                  rows={4}
                  maxLength={1_200}
                  placeholder={t.reasoningHint}
                  aria-describedby="reasoning-help"
                />
                <small id="reasoning-help">{result ? t.attemptRecorded : t.reasoningHint}</small>
              </label>

              {result && (
                <div aria-live="polite" className={`assessment-diagnosis ${result.correct ? 'is-correct' : 'needs-intervention'}`}>
                  <div className={`flex items-center gap-2 text-sm font-black ${result.correct ? 'text-teal-800 dark:text-teal-200' : 'text-amber-900 dark:text-amber-200'}`}>
                    {result.correct ? <CheckCircle2 className="h-5 w-5" /> : <AlertCircle className="h-5 w-5" />}
                    {result.correct ? t.correct : t.incorrect}
                  </div>
                  {!result.correct && (
                    <>
                      <div className="diagnosis-heading"><div><span>{t.diagnosis}</span><h3>{result.misconception || t.incorrect}</h3></div><ShieldCheck aria-hidden="true" /></div>
                      <p className="diagnosis-note">{t.diagnosisNote}</p>
                      <blockquote>{reasoning}</blockquote>
                      <div className="diagnosis-intervention"><span>{t.intervention}</span><p>{result.explanation}</p></div>
                    </>
                  )}
                  {result.correct && <><h3 className="mt-4 text-xs font-black text-[var(--muted)]">{t.explanation}</h3><p className="mt-1 text-sm leading-7 text-[var(--text)]">{result.explanation}</p></>}
                </div>
              )}

              {error && <ErrorMessage text={error} />}
              <div className="mt-6 flex justify-end">
                {!result ? (
                  <button type="button" disabled={checking || selected === null || reasoning.trim().length < 8} onClick={() => void checkAnswer()} className="premium-button disabled:cursor-not-allowed disabled:opacity-50">
                    {checking ? <><Loader2 className="h-4 w-4 animate-spin" />{t.checking}</> : <><CheckCircle2 className="h-4 w-4" />{t.submit}</>}
                  </button>
                ) : (
                  <button type="button" onClick={advance} className="premium-button">{index === quiz.questions.length - 1 ? t.finish : result.correct ? t.next : t.retryApplication}<Chevron className="h-4 w-4" /></button>
                )}
              </div>
            </section>

            {quiz.sources.length > 0 && <SourceStrip quiz={quiz} language={language} />}
          </div>
        )}

        {quiz && attempt && (
          <ResultPanel attempt={attempt} session={completedSession || undefined} language={language} onRetry={() => reset(true)} onNew={() => reset(false)} />
        )}
      </div>
    </main>
  );
}

function createQuizEvidenceSession(quiz: GeneratedQuiz, results: GradeResult[], reasonings: string[], mastery: number, language: 'ar' | 'en'): LearningSession {
  const sessionId = crypto.randomUUID();
  const now = new Date();
  const wrong = results.find((item) => !item.correct && item.misconception);
  const occurredAt = () => new Date(now.getTime() + events.length * 10).toISOString();
  const events: LearningEvent[] = [];
  const add = (input: Omit<LearningEvent, 'id' | 'sessionId' | 'sequence' | 'conceptKey' | 'occurredAt'>) => events.push({
    ...input,
    id: crypto.randomUUID(),
    sessionId,
    sequence: events.length + 1,
    conceptKey: quiz.topic.toLowerCase().replace(/\s+/g, '-').slice(0, 160),
    occurredAt: occurredAt(),
  });
  const primarySource = quiz.sources[0]?.title || '';
  add({ type: 'diagnostic_started', title: language === 'ar' ? 'اختبار تشخيصي' : 'Diagnostic assessment', summary: `${quiz.questions.length} ${language === 'ar' ? 'أسئلة تطبيقية' : 'application questions'}` });
  add({
    type: 'attempt_submitted',
    title: language === 'ar' ? 'محاولة مع تفسير طريقة التفكير' : 'Attempt with reasoning',
    summary: `${results.filter((item) => item.correct).length}/${quiz.questions.length} · ${mastery}%`,
    payload: { reasonings: reasonings.slice(0, quiz.questions.length), correct: results.map((item) => item.correct) },
  });
  if (wrong) {
    add({ type: 'misconception_detected', title: language === 'ar' ? 'التباس محتمل' : 'Likely misconception', summary: wrong.misconception.slice(0, 800), misconception: normalizeMisconception(wrong.misconception), confidence: 0.7 });
    add({ type: 'intervention_completed', title: language === 'ar' ? 'تفسير موجّه' : 'Targeted explanation', summary: wrong.explanation.slice(0, 1_000) });
    // A real retry = a correct answer to a question that came after the first
    // wrong one, i.e. post-intervention evidence، never inferred from
    // unrelated correct answers elsewhere in the quiz.
    const firstWrongIndex = results.findIndex((item) => !item.correct);
    const postInterventionCorrect = firstWrongIndex >= 0 ? results.slice(firstWrongIndex + 1).filter((item) => item.correct).length : 0;
    if (postInterventionCorrect > 0) {
      add({ type: 'retry_submitted', title: language === 'ar' ? 'محاولة تطبيقية جديدة بعد التدخل' : 'Post-intervention retry', summary: language === 'ar' ? `أجاب المتعلم إجابة صحيحة على ${postInterventionCorrect} سؤال جديد بعد التدخل.` : `The learner answered ${postInterventionCorrect} new question(s) correctly after the intervention.` });
    }
  }
  add({ type: 'evidence_created', title: language === 'ar' ? 'دليل تقييم تكويني' : 'Formative assessment evidence', summary: language === 'ar' ? 'نتيجة مصححة على الخادم مع المهارات المقاسة.' : 'Server-graded result with measured skills.' });
  const reviewDueAt = scheduleReviewFromScore(mastery, now);
  add({ type: 'review_scheduled', title: language === 'ar' ? 'مراجعة مجدولة' : 'Review scheduled', summary: new Intl.DateTimeFormat(language === 'ar' ? 'ar-EG' : 'en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(reviewDueAt)), payload: { dueAt: reviewDueAt } });
  return {
    id: sessionId,
    conceptKey: quiz.topic.toLowerCase().replace(/\s+/g, '-').slice(0, 160),
    conceptAr: quiz.topic,
    conceptEn: quiz.topic,
    sourceTitle: primarySource || undefined,
    classification: primarySource ? 'verified_source' : 'inferred',
    mastery: { concept: mastery, explanation: Math.max(0, mastery - 5), application: mastery, recall: 0, sourceUse: primarySource ? 60 : 0 },
    status: 'evidence_ready',
    reviewDueAt,
    events,
    createdAt: now.toISOString(),
    updatedAt: events[events.length - 1]?.occurredAt || now.toISOString(),
  };
}

function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) {
  return <label><span className="text-xs font-black text-[var(--muted)]">{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} maxLength={80} placeholder={placeholder} className="mt-2 h-12 w-full rounded-2xl border border-[var(--border)] bg-[var(--soft)] px-4 text-sm font-bold text-[var(--text)] outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-500/10" /></label>;
}

function ErrorMessage({ text }: { text: string }) {
  return <p role="alert" className="mt-4 flex items-center gap-2 rounded-2xl border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-700 dark:border-rose-400/20 dark:bg-rose-500/10 dark:text-rose-200"><AlertCircle className="h-4 w-4 shrink-0" />{text}</p>;
}

function MasterySummary({ language }: Props) {
  const t = copy[language];
  const stats = getMasteryStats();
  return <aside className="premium-card p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-[var(--muted)]">{t.history}</p><p className="mt-2 text-3xl font-black text-[var(--text)]">{stats.mastery}%</p></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-amber-100 text-amber-700 dark:bg-amber-500/10 dark:text-amber-300"><BarChart3 className="h-6 w-6" /></span></div>{stats.attempts === 0 ? <p className="mt-6 text-sm leading-7 text-[var(--muted)]">{t.noHistory}</p> : <div className="mt-6 space-y-4"><Stat label={t.attempts} value={String(stats.attempts)} /><Stat label={t.questions} value={String(stats.totalQuestions)} />{stats.weakestTopics[0] && <div className="rounded-2xl bg-[var(--soft)] p-4"><p className="text-[10px] font-black uppercase tracking-wider text-[var(--muted)]">{t.weakest}</p><p className="mt-2 text-sm font-black text-[var(--text)]">{stats.weakestTopics[0].topic}</p><p className="mt-1 text-xs font-black text-amber-700 dark:text-amber-300">{stats.weakestTopics[0].mastery}%</p></div>}</div>}</aside>;
}

function Stat({ label, value }: { label: string; value: string }) {
  return <div className="flex items-center justify-between border-b border-[var(--border)] pb-3"><span className="text-xs font-bold text-[var(--muted)]">{label}</span><span className="text-sm font-black text-[var(--text)]">{value}</span></div>;
}

function SourceStrip({ quiz, language }: { quiz: GeneratedQuiz; language: 'ar' | 'en' }) {
  const t = copy[language];
  return <section className="mt-6 rounded-3xl border border-[var(--border)] bg-[var(--panel)] p-5"><div className="flex items-center gap-2"><BookOpenCheck className="h-4 w-4 text-violet-600" /><h2 className="text-xs font-black text-[var(--text)]">{t.sources}</h2></div><p className="mt-2 text-[10px] leading-5 text-[var(--muted)]">{t.sourcesNote}</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{quiz.sources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-2 rounded-2xl border border-[var(--border)] bg-[var(--soft)] p-3 text-xs font-black text-[var(--text)] hover:border-violet-400"><span className="line-clamp-2">{source.title}</span><ExternalLink className="h-3.5 w-3.5 shrink-0 text-violet-600" /></a>)}</div></section>;
}

function ResultPanel({ attempt, session, language, onRetry, onNew }: { attempt: QuizAttempt; session?: LearningSession; language: 'ar' | 'en'; onRetry: () => void; onNew: () => void }) {
  const t = copy[language];
  const label = attempt.mastery >= 80 ? t.mastered : attempt.mastery >= 60 ? t.developing : t.revisit;
  const Arrow = language === 'ar' ? ArrowLeft : ArrowRight;
  const Back = language === 'ar' ? ChevronRight : ChevronLeft;
  return <div className="mx-auto max-w-5xl space-y-6"><section className="assessment-result"><div className="assessment-result-heading"><div className="flex items-center gap-2 text-xs font-black"><ShieldCheck className="h-5 w-5" />{t.result}</div><h1>{label}</h1><p>{attempt.topic}</p><div className="assessment-result-metrics"><ResultMetric label={t.score} value={`${attempt.score}/${attempt.total}`} /><ResultMetric label={t.mastery} value={`${attempt.mastery}%`} /><ResultMetric label={t.resultEvidence} value={session ? '1' : '—'} /></div></div><div className="assessment-result-body"><h2>{t.skill}</h2><p>{t.resultEvidenceBody}</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{attempt.skills.map((skill, index) => <div key={`${skill.skill}-${index}`} className={`flex items-center gap-3 rounded-2xl border p-3 text-xs font-bold ${skill.correct ? 'border-teal-200 bg-teal-50 text-teal-900 dark:border-teal-400/20 dark:bg-teal-500/10 dark:text-teal-100' : 'border-amber-200 bg-amber-50 text-amber-950 dark:border-amber-400/20 dark:bg-amber-500/10 dark:text-amber-100'}`}>{skill.correct ? <CheckCircle2 className="h-4 w-4 shrink-0" /> : <AlertCircle className="h-4 w-4 shrink-0" />}{skill.skill}</div>)}</div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={onRetry} className="premium-button justify-center"><RotateCcw className="h-4 w-4" />{t.retry}<Arrow className="h-4 w-4" /></button><button type="button" onClick={onNew} className="premium-button-secondary justify-center"><Back className="h-4 w-4" />{t.newTopic}</button></div></div></section><LearningEvidencePanel session={session} language={language} /></div>;
}

function ResultMetric({ label, value }: { label: string; value: string }) {
  return <div><p>{label}</p><strong>{value}</strong></div>;
}
