import { FormEvent, useMemo, useState } from 'react';
import { AlarmClock, BrainCircuit, Check, Clock3, Layers3, Plus, RotateCcw, Sparkles, Trash2, TrendingUp } from 'lucide-react';
import { createReviewCard, dueReviewCards, gradeReviewCard, loadReviewCards, removeReviewCard, type ReviewGrade } from '@/lib/spacedReview';
import { recordStudyAction } from '@/lib/studyProgress';
import MemoryTimeline from '@/components/learning/MemoryTimeline';

const copy = {
  ar: { eyebrow: 'ذاكرة فَهيم', title: 'راجع قبل أن تنسى، لا بعده.', body: 'جدولة متباعدة حقيقية: كل تقييم يغيّر موعد البطاقة وصعوبتها. لا نقاط وهمية؛ الهدف أن تظهر البطاقة في اللحظة التي تحتاجها فيها.', due: 'مستحق الآن', tomorrow: 'خلال 24 ساعة', mature: 'ذاكرة مستقرة', total: 'إجمالي البطاقات', add: 'أضف بطاقة', front: 'السؤال أو المفهوم', back: 'الإجابة المختصرة', subject: 'المادة', save: 'حفظ البطاقة', reveal: 'اكشف الإجابة', again: 'نسيت', hard: 'صعب', good: 'جيد', easy: 'سهل', empty: 'لا توجد مراجعات مستحقة الآن.', emptyBody: 'أضف بطاقة جديدة أو عد في موعد المراجعة القادم.', all: 'كل البطاقات', interval: 'الفاصل', days: 'يوم', delete: 'حذف', answer: 'الإجابة', method: 'خوارزمية تكيفية مستوحاة من SM-2 مع خطوات تعلم قصيرة.' },
  en: { eyebrow: 'Fahim memory', title: 'Review before you forget—not after.', body: 'Real spaced scheduling: every rating changes the card’s next due date and difficulty. No vanity points; the card appears when you need it.', due: 'Due now', tomorrow: 'Next 24 hours', mature: 'Stable memory', total: 'Total cards', add: 'Add card', front: 'Question or concept', back: 'Concise answer', subject: 'Subject', save: 'Save card', reveal: 'Reveal answer', again: 'Again', hard: 'Hard', good: 'Good', easy: 'Easy', empty: 'Nothing is due right now.', emptyBody: 'Add a new card or return at the next scheduled review.', all: 'All cards', interval: 'Interval', days: 'days', delete: 'Delete', answer: 'Answer', method: 'Adaptive scheduling inspired by SM-2 with short learning steps.' },
} as const;
const grades: { key: ReviewGrade; className: string }[] = [{ key: 'again', className: 'bg-[#D95D39] text-white' }, { key: 'hard', className: 'bg-[#F2B84B] text-[#14213D]' }, { key: 'good', className: 'bg-[#0F766E] text-white' }, { key: 'easy', className: 'bg-[#173F5F] text-white' }];

export default function SpacedReview({ language }: { language: 'ar' | 'en' }) {
  const t = copy[language]; const [cards, setCards] = useState(() => loadReviewCards()); const [activeId, setActiveId] = useState(() => dueReviewCards()[0]?.id || ''); const [revealed, setRevealed] = useState(false); const [adding, setAdding] = useState(false);
  const [front, setFront] = useState(''); const [back, setBack] = useState(''); const [subject, setSubject] = useState('');
  const stats = useMemo(() => { const now = new Date(); const tomorrow = new Date(now.getTime() + 86_400_000); return { total: cards.length, due: cards.filter((card) => new Date(card.dueAt) <= now).length, tomorrow: cards.filter((card) => { const date = new Date(card.dueAt); return date > now && date <= tomorrow; }).length, mature: cards.filter((card) => card.intervalDays >= 21).length }; }, [cards]); const due = useMemo(() => cards.filter((card) => new Date(card.dueAt) <= new Date()).sort((a, b) => a.dueAt.localeCompare(b.dueAt)), [cards]); const active = cards.find((card) => card.id === activeId) || due[0];
  const add = (event: FormEvent) => { event.preventDefault(); if (front.trim().length < 2 || back.trim().length < 2) return; const card = createReviewCard(front, back, subject); setCards(loadReviewCards()); setActiveId(card.id); setFront(''); setBack(''); setAdding(false); setRevealed(false); };
  const grade = (value: ReviewGrade) => { if (!active) return; gradeReviewCard(active.id, value); recordStudyAction('session', active.subject || active.front); const next = due.filter((card) => card.id !== active.id)[0]; setCards(loadReviewCards()); setActiveId(next?.id || ''); setRevealed(false); };
  const remove = (id: string) => { removeReviewCard(id); setCards(loadReviewCards()); if (activeId === id) setActiveId(''); };
  return <main className="min-h-[80vh] bg-[var(--surface)] pb-20"><section className="atlas-grid border-b border-[var(--border)] bg-[var(--paper)] py-14 dark:bg-[#0b1116] sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="atlas-kicker"><BrainCircuit className="h-4 w-4" />{t.eyebrow}</p><div className="mt-5 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><h1 className="atlas-display max-w-4xl text-4xl sm:text-6xl">{t.title}</h1><p className="mt-5 max-w-3xl leading-8 text-[var(--muted)]">{t.body}</p><p className="mt-4 flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-[#0F766E]"><Sparkles className="h-3.5 w-3.5" />{t.method}</p></div><button type="button" onClick={() => setAdding((value) => !value)} className="atlas-primary"><Plus className="h-4 w-4" />{t.add}</button></div></div></section>
    <div className="mx-auto max-w-7xl px-4 pt-8 sm:px-6 lg:px-8"><section className="grid border-y border-[var(--border)] sm:grid-cols-4">{[[t.due, stats.due, AlarmClock], [t.tomorrow, stats.tomorrow, Clock3], [t.mature, stats.mature, TrendingUp], [t.total, stats.total, Layers3]].map(([label, value, Icon], index) => { const MetricIcon = Icon as typeof AlarmClock; return <div key={String(label)} className={`p-5 ${index ? 'border-t border-[var(--border)] sm:border-s sm:border-t-0' : ''}`}><MetricIcon className="h-4 w-4 text-[#D95D39]" /><p className="mt-5 text-3xl font-black text-[var(--text)]">{String(value)}</p><p className="mt-1 text-[10px] font-black uppercase tracking-widest text-[var(--muted)]">{String(label)}</p></div>; })}</section>
      {adding ? <form onSubmit={add} className="mt-8 grid gap-4 border-2 border-[var(--text)] bg-[var(--panel)] p-5 md:grid-cols-2"><label><span className="atlas-label">{t.front}</span><textarea value={front} onChange={(event) => setFront(event.target.value)} rows={3} className="atlas-field mt-2" /></label><label><span className="atlas-label">{t.back}</span><textarea value={back} onChange={(event) => setBack(event.target.value)} rows={3} className="atlas-field mt-2" /></label><label><span className="atlas-label">{t.subject}</span><input value={subject} onChange={(event) => setSubject(event.target.value)} className="atlas-field mt-2 h-12" /></label><button disabled={front.trim().length < 2 || back.trim().length < 2} className="atlas-primary self-end justify-center disabled:opacity-40"><Check className="h-4 w-4" />{t.save}</button></form> : null}
      <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_20rem]"><section>{active ? <article className="min-h-[24rem] border-2 border-[var(--text)] bg-[var(--panel)] p-6 sm:p-10"><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-[.2em] text-[#D95D39]">{active.subject || t.eyebrow}</span><span className="text-[10px] font-bold text-[var(--muted)]">{new Date(active.dueAt).toLocaleDateString(language === 'ar' ? 'ar-EG' : 'en-GB')}</span></div><h2 className="mt-12 max-w-3xl text-2xl font-black leading-10 text-[var(--text)] sm:text-3xl">{active.front}</h2>{revealed ? <div className="mt-10 border-s-4 border-[#0F766E] bg-[#0F766E]/8 p-5"><p className="text-[10px] font-black uppercase tracking-widest text-[#0F766E]">{t.answer}</p><p className="mt-3 whitespace-pre-wrap text-base font-bold leading-8 text-[var(--text)]">{active.back}</p></div> : <button type="button" onClick={() => setRevealed(true)} className="atlas-primary mt-12"><RotateCcw className="h-4 w-4" />{t.reveal}</button>}{revealed ? <div className="mt-8 grid grid-cols-2 gap-2 sm:grid-cols-4">{grades.map((item) => <button type="button" key={item.key} onClick={() => grade(item.key)} className={`px-4 py-3 text-xs font-black ${item.className}`}>{t[item.key]}</button>)}</div> : null}</article> : <div className="grid min-h-[24rem] place-items-center border-y border-dashed border-[var(--border)] text-center"><div><Check className="mx-auto h-8 w-8 text-[#0F766E]" /><h2 className="mt-4 text-xl font-black text-[var(--text)]">{t.empty}</h2><p className="mt-2 text-sm text-[var(--muted)]">{t.emptyBody}</p></div></div>}</section>
        <aside><div className="flex items-center justify-between border-b-2 border-[var(--text)] pb-3"><h2 className="text-sm font-black text-[var(--text)]">{t.all}</h2><span className="text-[10px] font-black text-[#D95D39]">{cards.length}</span></div><div className="max-h-[34rem] divide-y divide-[var(--border)] overflow-y-auto">{cards.map((card) => <article key={card.id} className="py-4"><div className="flex gap-3"><button type="button" onClick={() => { setActiveId(card.id); setRevealed(false); }} className="min-w-0 flex-1 text-start"><p className="line-clamp-2 text-xs font-black leading-5 text-[var(--text)]">{card.front}</p><p className="mt-1 text-[9px] font-bold text-[var(--muted)]">{t.interval}: {card.intervalDays} {t.days}</p></button><button type="button" onClick={() => remove(card.id)} title={t.delete} aria-label={t.delete} className="text-[var(--muted)] hover:text-[#D95D39]"><Trash2 className="h-3.5 w-3.5" /></button></div></article>)}</div></aside></div>
      <MemoryTimeline cards={cards} language={language} onSelect={(id)=>{setActiveId(id);setRevealed(false);window.scrollTo({top:0,behavior:'auto'});}} />
    </div></main>;
}
